# Generated by Django 2.1.1 on 2018-10-29 11:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_foto', verbose_name='Фото')),
                ('money', models.FloatField(default=0, verbose_name='Сумма')),
                ('ref_id', models.CharField(default=None, max_length=10, null=True, verbose_name='Реферальное id')),
                ('ref_procent', models.FloatField(default=0.15, verbose_name='Процент с рефералов')),
                ('valute', models.CharField(default='', max_length=3, verbose_name='Валюта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('site', models.CharField(max_length=200, verbose_name='Сайт')),
                ('image', models.ImageField(blank=True, upload_to='static/banksImages', verbose_name='Картинка')),
                ('ignore', models.BooleanField(default=False, verbose_name='Игнорировать')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=96, verbose_name='Ключ')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Смена пароля',
                'verbose_name_plural': 'Смена паролей',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='DataReferal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_friends', models.FloatField(default=0, verbose_name='Кол-во рефералов')),
                ('profit_from_friends', models.FloatField(default=0, verbose_name='Прибыль от друзей')),
                ('contrib_friends', models.FloatField(default=0, verbose_name='Взнос друзей')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные по рефреалу',
                'verbose_name_plural': 'Данные по рефреалам',
                'ordering': ['count_friends'],
            },
        ),
        migrations.CreateModel(
            name='InviteRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ref_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_or_email', models.CharField(max_length=100, verbose_name='Email or Phone')),
                ('message', models.TextField(max_length=2000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent_profit', models.FloatField(default=0, verbose_name='Процент прибыли')),
                ('money', models.FloatField(default=0, verbose_name='Прибыль')),
                ('start_valute', models.CharField(max_length=3, verbose_name='Начальная валюта')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('route_profit', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Маршрут')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['procent_profit'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('ADD', 'Пополнить счет'), ('CON', 'Вывод средств'), ('REF', 'Реферальная программа')], default='ADD', max_length=2, verbose_name='Тип транзакции')),
                ('money', models.FloatField(verbose_name='Сумма')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['date'],
            },
        ),
    ]
