# Generated by Django 2.1.1 on 2018-11-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181101_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareferal',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datareferal', to=settings.AUTH_USER_MODEL),
        ),
    ]
