# Generated by Django 2.1.1 on 2018-11-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181101_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ref_id',
            new_name='id_ref',
        ),
    ]
