# Generated by Django 2.1.1 on 2018-11-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20181101_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteref',
            name='ref_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
