# Generated by Django 2.1.1 on 2018-11-02 14:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181101_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_profit',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='route',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
