# Generated by Django 2.1.1 on 2018-11-02 14:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20181102_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_profit',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Маршрут'),
        ),
    ]
