# Generated by Django 2.1.1 on 2018-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_datareferal_profit_in_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='Допущено к выводу'),
        ),
    ]
