# Generated by Django 2.1.1 on 2018-11-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20181122_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('ADD', 'Пополнить счет'), ('CON', 'Вывод средств'), ('REF', 'Реферальная программа')], default='ADD', max_length=3, verbose_name='Тип транзакции'),
        ),
    ]
