# Generated by Django 2.1.1 on 2018-11-27 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20181122_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepassword',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
