# Generated by Django 2.1.1 on 2018-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20181130_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='image',
            field=models.ImageField(blank=True, upload_to='banks_images', verbose_name='Картинка'),
        ),
    ]
