import re

data = [
    {'name': 'Alpha bank', 'site': 'http://www.alphabank.al/en/', 'country': 'Албания', 'ignore': False,
     'address': 'г. Берат, Албания', 'phoneNumber': '042 278 500'},
    {'name': 'Credit bank of albania', 'site': 'http://www.creditbankofalbania.al/index.php/en/', 'country': 'Албания',
     'ignore': False, 'address': 'г. Тирана, Албания', 'phoneNumber': '+355 4 2 272166'},
    {'name': 'FiBank', 'site': 'https://www.fibank.al/en/page/1672', 'country': 'Албания', 'ignore': False,
     'address': 'г. Тирана, Албания', 'phoneNumber': '(+355 4) 2276 702; (+355 4) 2276 703'},
    {'name': 'Banka Kombetare Tregtre', 'site': 'http://www.bkt.com.al/Main.aspx', 'country': 'Албания',
     'ignore': False, 'address': 'г. Тирана, Албания', 'phoneNumber': '355/4/ 2 250 955'},
    {'name': 'Credins', 'site': 'https://www.bankacredins.com/en/index.php/services/treasury/exchange/',
     'country': 'Албания', 'ignore': False, 'address': 'г. Тирана, Албания', 'phoneNumber': '+355 4 53 53 000'},
    {'name': 'Internetional Commercial Bank', 'site': 'http://www.icbank-albania.com/index.php/en/',
     'country': 'Албания', 'ignore': False, 'address': 'г. Тирана, Албания',
     'phoneNumber': '4 2256 254 / 2254 372 / 2235 406'},
    {'name': 'Intesa Sanpaolo bank', 'site': 'http://www.intesasanpaolobank.al/web/Kursi_i_kembimit.php',
     'country': 'Албания', 'ignore': False, 'address': 'г. Тирана, Албания',
     'phoneNumber': '+355 4 22 76 000/ 222/ 223'},
    {'name': 'Raiffeisen Bank', 'site': 'https://www.raiffeisen.al/en/page/exchange/', 'country': 'Албания',
     'ignore': False, 'address': 'г. Тирана, Албания', 'phoneNumber': '00355 4 2274 566'},
    {'name': 'Union Bank', 'site': 'https://www.unionbank.al/', 'country': 'Албания', 'ignore': False,
     'address': 'г. Тирана, Албания', 'phoneNumber': '+35542389090'},
    {'name': 'Ineco bank', 'site': 'https://www.inecobank.am/en/home', 'country': 'Армения', 'ignore': False,
     'address': 'г. Ереван, Армения', 'phoneNumber': '+374 10 510510'},
    {'name': 'Anelik bank', 'site': 'http://www.anelik.am/ru/', 'country': 'Армения', 'ignore': False,
     'address': 'г. Ереван, Армения', 'phoneNumber': '(374-10) 228717, 228744'},
    {'name': 'Ardshin bank', 'site': 'https://www.ardshinbank.am/index.php', 'country': 'Армения', 'ignore': False,
     'address': 'г. Ереван, Армения', 'phoneNumber': '(+37412) 22 22 22'},
    {'name': 'Ameria bank', 'site': 'https://www.ameriabank.am/default.aspx?lang=4', 'country': 'Армения',
     'ignore': False, 'address': 'г. Ереван, Армения', 'phoneNumber': '+37410 56 11 11'},
    {'name': 'Armeconombank', 'site': 'http://www.aeb.am/', 'country': 'Армения', 'ignore': False,
     'address': 'г. Ереван, Армения', 'phoneNumber': '+374 10 510-910; +374 8000 8686'},
    {'name': 'AccessBank', 'site': 'http://www.accessbank.az/ru', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '(+99412) 490 80 10'},
    {'name': 'Azer Turk Bank', 'site': 'http://ru.azerturkbank.az/?course', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '+994 12 4041454'},
    {'name': 'AFB bank (ОАО)', 'site': 'https://afb.az/az', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '(+994 12) 565 65 65'},
    {'name': 'Bank Respublicka', 'site': 'https://www.bankrespublika.az/', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '+994 12 144'},
    {'name': 'Mugan bank', 'site': 'http://www.muganbank.az/az/', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '+994 12 5643511'},
    {'name': 'Amrahbank', 'site': 'http://www.amrahbank.az/', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '+994 12 987'},
    {'name': 'Gunay bank', 'site': 'http://www.gunaybank.com/currency', 'country': 'Азербайджан', 'ignore': False,
     'address': 'г. Баку, Азербайджан', 'phoneNumber': '+994 12 4980455'},
    {'name': 'Unibank', 'site': 'https://www.unibank.az/ru/site/index', 'country': 'Азербайджан', 'ignore': False,
     'address': 'Азербайджан, Баку', 'phoneNumber': '117'},
    {'name': 'ОАО «АСБ Беларусбанк»', 'site': 'https://belarusbank.by/', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г. Минск, Беларусь', 'phoneNumber': '+375 (17) 218-84-31'},
    {'name': 'ЗАО «Альфа-Банк»', 'site': 'https://www.alfabank.by/', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г. Минск, Беларусь', 'phoneNumber': '+375-44-733-33-32'},
    {'name': 'ОАО белагропромбанк', 'site': 'http://www.belapb.by/rus/', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г. Минск, Беларусь', 'phoneNumber': '+375-17-218-57-77'},
    {'name': 'ЗАО «БСБ Банк»', 'site': 'https://www.bsb.by/private/currency/all-rates/card-rates/',
     'country': 'Белоруссия', 'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '+375-17-306-20-40'},
    {'name': 'ОАО "Паритетбанк"', 'site': 'http://www.paritetbank.by/services/private/card/cards/',
     'country': 'Белоруссия', 'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '+375-44-545-49-49'},
    {'name': 'ЗАО «РРБ-Банк»', 'site': 'https://rrb.by/', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г. Минск, Беларусь', 'phoneNumber': '+375-17-306-02-02'},
    {'name': 'Банк Москва-Минск', 'site': 'https://www.mmbank.by/personal/currency_exchange/', 'country': 'Белоруссия',
     'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '(+375 17) 239-19-19'},
    {'name': 'ЗАО «Банк «Решение»', 'site': 'https://rbank.by/currency/', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г.Минск, Беларусь', 'phoneNumber': '+375 29 1 293 293'},
    {'name': 'ОАО «Банк БелВЭБ»',
     'site': 'https://www.belveb.by/individual/uslugi-i-obsluzhivanie/valyutno-obmennye-operatsii/kursy-po-operatsiyam-s-kartochkami/',
     'country': 'Белоруссия', 'ignore': False, 'address': 'г.Минск, Беларусь', 'phoneNumber': '+375 (17) 388-48-18'},
    {'name': 'ОАО «Белорусский народный банк»', 'site': 'https://www.bnb.by/kursy-valyut/fizicheskim-litsam/',
     'country': 'Белоруссия', 'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '+375 (17) 309-7-309'},
    {'name': 'ЗАО «БТА Банк» ', 'site': 'http://www.btabank.by/ru/currency', 'country': 'Белоруссия', 'ignore': False,
     'address': 'г.Минск, Беларусь', 'phoneNumber': '+375 (17) 334-54-34'},
    {'name': 'ОАО «БПС-Сбербанк»',
     'site': 'https://www.bps-sberbank.by/43257f17004e948d/currency_rates?openform&tabnum=3', 'country': 'Белоруссия',
     'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '+375 (29) 5 148 148'},
    {'name': 'ЗАО «ВТБ»', 'site': 'https://www.vtb-bank.by/chastnym-licam/valutno-obmennye-operacii',
     'country': 'Белоруссия', 'ignore': False, 'address': 'г. Минск, Беларусь', 'phoneNumber': '+375 (17) 309-15-15'},
    {'name': 'Bulgarian Development Bank', 'site': 'http://www.bbr.bg/', 'country': 'Болгария', 'ignore': False,
     'address': 'г. София, Болгария', 'phoneNumber': '0700 10 000'},
    {'name': 'АО Центральный Кооперативный Банк', 'site': 'http://www.ccbank.bg/en/currency-rates/',
     'country': 'Болгария', 'ignore': False, 'address': 'г. София, Болгария',
     'phoneNumber': '(02) 9266 668, (02) 9266 666'},
    {'name': 'First Investment Bank', 'site': 'https://www.fibank.bg/en/currency-rates/page/1672',
     'country': 'Болгария', 'ignore': False, 'address': 'г. София, Болгария',
     'phoneNumber': '+359 2 818 0006, +359 2 818 0007'},
    {'name': '"Eurobank Bulgaria" AD', 'site': 'https://www.postbank.bg/bg-BG/CCYRates', 'country': 'Болгария',
     'ignore': False, 'address': 'г. София, Болгария', 'phoneNumber': '0700 18 555'},
    {'name': '"Raiffeisenbank Bulgaria" EAD',
     'site': 'https://www.rbb.bg/bg/individualni-klienti/polezni-instrumenti/bankirane/valutni-kursove/',
     'country': 'Болгария', 'ignore': False, 'address': 'г. София, Болгария', 'phoneNumber': '0700 11 227'},
    {'name': 'Tbi Bank', 'site': 'https://tbibank.bg/en', 'country': 'Болгария', 'ignore': False,
     'address': 'г. Пловдив, Болгария', 'phoneNumber': '0700 17 571'},
    {'name': 'Piraeus Bank',
     'site': 'http://www.piraeusbank.gr/en/idiwtes/epitokia-deltia-timon/imerisio-deltio-timon-synallagmatos-trapezogrammation',
     'country': 'Греция', 'ignore': False, 'address': 'г. Афины, Греция', 'phoneNumber': '0030 210 3288000'},
    {'name': 'National Bank of Greece', 'site': 'https://www.nbg.gr/en/treasury', 'country': 'Греция', 'ignore': False,
     'address': 'Греция, Афины', 'phoneNumber': '+30 210 48 48 484'},
    {'name': 'АО "АТФБанк"', 'site': 'https://www.atfbank.kz/curs/beznal/', 'country': 'Казахстан', 'ignore': False,
     'address': 'г. Алматы, Казахстан', 'phoneNumber': '8 8000 800 283'},
    {'name': 'АО «Bank RBK»', 'site': 'https://www.bankrbk.kz/rus', 'country': 'Казахстан', 'ignore': False,
     'address': 'г. Алматы, Казахстан', 'phoneNumber': '+7 (727) 330-90-30'},
    {'name': 'АО "Евразийский банк"', 'site': 'https://www.eubank.kz/', 'country': 'Казахстан', 'ignore': False,
     'address': 'г. Алматы, Казахстан', 'phoneNumber': '+7 (727) 332-77-22'},
    {'name': 'АО «Казкоммерцбанк»', 'site': 'http://www.qazkom.kz/', 'country': 'Казахстан', 'ignore': False,
     'address': 'г. Алматы, Казахстан', 'phoneNumber': '+7 (727) 2-585-185'},
    {'name': 'ЗАО «БТА Банк»', 'site': 'http://www.btabank.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 (312) 90 50 50; +996 (552) 90 50 50'},
    {'name': 'ОАО «Коммерческий банк КЫРГЫЗСТАН»', 'site': 'http://www.cbk.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 (312) 61 33 33'},
    {'name': 'ЗАО «Банк Компаньон»', 'site': 'http://www.kompanion.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 (312)  33 88 00 '},
    {'name': 'ЗАО «Банк Азии»', 'site': 'http://www.bankasia.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 312 551182'},
    {'name': 'ОАО "Капитал Банк"', 'site': 'http://www.capitalbank.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': ' +996 (312) 31 30 30'},
    {'name': 'ОАО «Кыргызкоммерцбанк»', 'site': 'http://kkb.kg/ru/about/currency/', 'country': 'Киргизия',
     'ignore': False, 'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 312 333 000'},
    {'name': 'ЗАО «Демир Кыргыз Интернэшнл Банк»', 'site': 'http://demirbank.kg/ru-ru', 'country': 'Киргизия',
     'ignore': False, 'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 (312) 610 610'},
    {'name': 'ОАО "Айыл Банк"', 'site': 'http://www.ab.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '(312) 68 00 00'},
    {'name': 'ОАО «Дос-Кредобанк»', 'site': 'http://www.doscredobank.kg/', 'country': 'Киргизия', 'ignore': False,
     'address': 'г. Бишкек, Киргизия', 'phoneNumber': '+996 (312) 98 69 89'},
    {'name': 'FinComBank', 'site': 'https://fincombank.com/ru/curs-valutar-pentru-carduri', 'country': 'Молдавия',
     'ignore': False, 'address': 'г. Кишинев, Молдова', 'phoneNumber': '(+373-22) 269-900'},
    {'name': 'BC Moldova Agroindbank SA', 'site': 'https://www.maib.md/ru/curs-valutar/', 'country': 'Молдавия',
     'ignore': False, 'address': 'г. Кишинев, Молдова', 'phoneNumber': '+373 22 / 268 999; (22) 856000'},
    {'name': 'BC "Mobiasbanca" SA', 'site': 'https://mobiasbanca.md/ru', 'country': 'Молдавия', 'ignore': False,
     'address': 'г. Кишинев, Молдова', 'phoneNumber': '022 256-456'},
    {'name': 'АО "EXIMBANK"', 'site': 'http://www.eximbank.com/rus/', 'country': 'Молдавия', 'ignore': False,
     'address': 'г. Кишинев, Молдова', 'phoneNumber': '+375-44-545-49-49'},
    {'name': 'BC "Victoriabank" SA', 'site': 'http://www.victoriabank.md/', 'country': 'Молдавия', 'ignore': False,
     'address': 'г. Кишинев, Молдова', 'phoneNumber': '+373 22 57 61 00'},
    {'name': 'ПАО "Азиатско-Тихоокеанский Банк"', 'site': 'http://www.atb.su/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 988-30-62, +7 (495) 988-30-61'},
    {'name': 'ООО Банк «Аверс»', 'site': 'https://aversbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Казань, Россия', 'phoneNumber': '8 (800) 700-43-21'},
    {'name': 'АО «АВТОГРАДБАНК»', 'site': 'http://www.avtogradbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Набережные Челны, Россия', 'phoneNumber': '8 (800) 2005-245'},
    {'name': 'АО «БКС Банк»', 'site': 'https://bcs-bank.com/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '8 800 500 7065'},
    {'name': ' ПАО «БИНБАНК»', 'site': 'https://www.binbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '8(800)200-50-75; 8 800 555-55-75'},
    {'name': 'АО АКБ "ЦентроКредит"', 'site': 'https://www.ccb.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 495 780 32 28'},
    {'name': 'ООО МИБ «ДАЛЕНА»', 'site': 'https://www.dalenabank.ru/private/exchange', 'country': 'Россия',
     'ignore': False, 'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 673-10-10'},
    {'name': 'ПАО "МОСОБЛБАНК"', 'site': 'http://www.mosoblbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 909-81-91; +7 (495) 909-81-98'},
    {'name': 'ПАО АКБ «Приморье»', 'site': 'http://www.primbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Владивосток, Россия', 'phoneNumber': '+7 (423) 226-06-00'},
    {'name': 'ПАО «Норвик Банк» (Вятка Банк)', 'site': 'https://www.vtkbank.ru/about/presscentr/currency/',
     'country': 'Россия', 'ignore': False, 'address': 'г. Киров, Россия', 'phoneNumber': '+7 800 1001 777'},
    {'name': 'ПАО «Донкомбанк»', 'site': 'http://www.doncombank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Ростов-на-Дону, Россия', 'phoneNumber': '+7(863) 207-60-60; 8-800-775-66-22'},
    {'name': 'АО КБ «ИНТЕРПРОМБАНК»', 'site': 'http://www.interprombank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 232–2050'},
    {'name': 'АО "Джей энд Ти Банк"', 'site': 'https://jtbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '8 (495) 662-45-45'},
    {'name': 'ООО Банк "ИТУРУП"', 'site': 'http://www.iturupbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Южно‐Сахалинск, Россия', 'phoneNumber': '+7 (4242) 72–73–12'},
    {'name': 'ПАО КБ «Центр-инвест»', 'site': 'https://www.centrinvest.ru/ru/fiz/bankovskie-karty/kursy-valyut/',
     'country': 'Россия', 'ignore': False, 'address': 'г Ростов-на-Дону, Россия', 'phoneNumber': ' 8 (863) 200-00-00'},
    {'name': 'ПАО «Дальневосточный банк»', 'site': 'https://www.dvbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Владивосток, Россия', 'phoneNumber': '8 800 333-00-11'},
    {'name': 'АО Банк "Национальный стандарт"', 'site': 'https://www.ns-bank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 (800) 250-33-00'},
    {'name': 'ООО «АвтоКредитБанк»', 'site': 'https://autokreditbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Казань, Россия', 'phoneNumber': '(843) 294-98-80, (8553) 39-43-24'},
    {'name': 'АО «Коммерческий Банк «Агропромкредит»', 'site': 'http://www.apkbank.ru/ru/msk/', 'country': 'Россия',
     'ignore': False, 'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 755-80-08'},
    {'name': 'ПАО «Акционерный коммерческий ипотечный банк «Акибанк»',
     'site': 'http://www.akibank.ru/chastnym-licam/obmen-valyuty/kursy/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7(8552) 77-33-88'},
    {'name': 'ПАО «Акционерный Коммерческий Банк «Актив Банк»', 'site': 'http://aktivbank.ru/', 'country': 'Россия',
     'ignore': False, 'address': 'г. Саранск, Россия', 'phoneNumber': '8(800)-30-20-050'},
    {'name': 'АО «Банк Акцепт»', 'site': 'https://www.akcept.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Новосибирск, Россия', 'phoneNumber': '8 800 100-27-37'},
    {'name': 'АКБ «Алмазэргиэнбанк» АО', 'site': 'https://www.albank.ru/ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Якутск, Россия', 'phoneNumber': '8 (4112) 34-22-22, 8 800 100-34-22'},
    {'name': 'ООО «Коммерческий банк «Алтайкапиталбанк»', 'site': 'http://capitalbank.ru/', 'country': 'Россия',
     'ignore': False, 'address': 'г. Барнаул, Россия', 'phoneNumber': '+7 (3852) 63-62-14'},
    {'name': 'ООО «Алтынбанк»', 'site': 'http://www.altynbank.com/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Казань, Россия', 'phoneNumber': '(843)520-51-00'},
    {'name': 'АО «Коммерческий банк «Ассоциация»', 'site': 'http://assotsiatsiyabank.ru/', 'country': 'Россия',
     'ignore': False, 'address': 'г. Нижний Новгород, Россия', 'phoneNumber': '+7(831)421-92-00'},
    {'name': 'АО «БайкалИнвестБанк»', 'site': 'http://www.baikalinvestbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Иркутск, Россия', 'phoneNumber': '+7 (499) 968-94-23'},
    {'name': 'ПАО «Коммерческий банк «Байкалкредобанк»', 'site': 'http://www.baikalcredobank.ru/irk/',
     'country': 'Россия', 'ignore': False, 'address': 'г. Иркутск, Россия', 'phoneNumber': '+7 (3952) 24-16-02'},
    {'name': 'ПАО «Балтийский Банк»', 'site': 'https://www.baltbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Санкт-Петербург, Россия', 'phoneNumber': '8-800-200-22-23'},
    {'name': 'Элита', 'site': 'http://bankelita.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Калуга, Россия', 'phoneNumber': '8 800 333 11 50'},
    {'name': 'ПАО «Химик»', 'site': 'http://www.bankhimik.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Нижегородская область, Россия', 'phoneNumber': '(8313) 26-16-08'},
    {'name': 'АКБ «Энергобанк» (ПАО)', 'site': 'http://energobank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Казань, Россия', 'phoneNumber': '+7 (843) 293-93-93'},
    {'name': 'ПАО «Энергомашбанк»', 'site': 'https://www.energomashbank.ru/main/person/exchange', 'country': 'Россия',
     'ignore': False, 'address': 'Санкт-Петербург, Россия', 'phoneNumber': '8 800 250-50-60'},
    {'name': 'КБ «ЭНЕРГОТРАНСБАНК» (АО)', 'site': 'http://www.energotransbank.com/', 'country': 'Россия',
     'ignore': False, 'address': 'Калининград, Россия', 'phoneNumber': '+7 (4012) 59-00-99'},
    {'name': 'АО «Эксперт Банк»', 'site': 'https://expertbank.com/#eb-page__section_3', 'country': 'Россия',
     'ignore': False, 'address': 'Москва, Россия', 'phoneNumber': '8 800 333 11 50'},
    {'name': 'АО «БАНК ХОЛМСК»', 'site': 'https://kholmskbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Южно-Сахалинск, Россия', 'phoneNumber': '(4242) 24–58–58'},
    {'name': 'АО «ТАТСОЦБАНК» ', 'site': 'https://tatsotsbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Казань, Россия', 'phoneNumber': '+7 (843) 299-1111'},
    {'name': '«Тимер Банк» (ПАО)', 'site': 'https://timerbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Казань, Россия', 'phoneNumber': '+7 (843) 525-74-74'},
    {'name': ' ТрансКапиталБанк', 'site': 'https://www.tkbbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Иваново, Россия', 'phoneNumber': '+7 495 777-41-50'},
    {'name': ' Трансстрой', 'site': 'https://www.transstroybank.ru/chastnym-klientam/konvertor-valyut/',
     'country': 'Россия', 'ignore': False, 'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 786-37-73'},
    {'name': 'ООО КБ «Уралфинанс»', 'site': 'http://www.uralfinance.com/bankomat/', 'country': 'Россия',
     'ignore': False, 'address': 'Екатеринбург, Россия', 'phoneNumber': '(343) 222-11-01 '},
    {'name': 'ПАО «Уралтрансбанк»', 'site': 'https://www.utb.ru/articles/poyasnenie', 'country': 'Россия',
     'ignore': False, 'address': 'Екатеринбург, Россия', 'phoneNumber': '+7 (343) 370-19-01'},
    {'name': 'ИКБР “Яринтербанк”', 'site': 'https://www.yarinterbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'Ярославль, Россия', 'phoneNumber': '+7 (4852) 32-86-58'},
    {'name': '"Ипотека-банк"', 'site': 'http://www.ipotekabank.uz/ru/', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Ташкент, Узбекистан', 'phoneNumber': '+998 (71) 150-89-56'},
    {'name': 'АКБ «Микрокредитбанк»', 'site': 'https://mikrokreditbank.uz/ru', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Ташкент, Узбекистан', 'phoneNumber': '(+99871) 202-99-99; (+998 71) 273-28-11'},
    {'name': 'АКБ "Туронбанк"', 'site': 'http://www.turonbank.uz/ru/sme/', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Ташкент, Узбекистан', 'phoneNumber': '+998 95 144-60-00'},
    {'name': 'ЧАКБ «Universalbank»', 'site': 'https://universalbank.uz/', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Коканд, Узбекистан', 'phoneNumber': '(+998 71) 200 11 10'},
    {'name': 'АО «Ziraat Bank Uzbekistan»', 'site': 'https://utbank.uz/ru', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Ташкент, Узбекистан', 'phoneNumber': '(+998 71) 273-83-24, 273-83-25'},
    {'name': 'Banka Citadele AS', 'site': 'https://www.citadele.lt/common/xml/ibval_eur.xml', 'country': 'Литва',
     'ignore': False, 'address': 'г. Вильнюс, Литва', 'phoneNumber': '+370 5 221 9091'},
    {'name': 'International Asset Bank AD',
     'site': 'http://www.iabank.bg/en/individual-clients/other-services/22-purchase-and-sale-of-currency/119-purchase-and-sale-of-currency#tab-informacja',
     'country': 'Болгария', 'ignore': False, 'address': 'г. София, Болгария', 'phoneNumber': '+359 2 812 0234'},
    {'name': 'Arion bank', 'site': 'https://www.arionbanki.is/english/#general', 'country': 'Исландия', 'ignore': False,
     'address': 'г. Хабнарфьордюр, Исландия', 'phoneNumber': '444 7000'},
    {'name': 'Íslandsbanki', 'site': 'https://www.islandsbanki.is/', 'country': 'Исландия', 'ignore': False,
     'address': 'г. Рейкьявик, Исландия', 'phoneNumber': '+354 440 4000'},
    {'name': 'AS SEB Bank', 'site': 'https://www.seb.ee/ru/kursy-valyut', 'country': 'Эстония', 'ignore': False,
     'address': 'г. Tornimäe, Эстония', 'phoneNumber': '665 5100'},
    {'name': 'Tallinn Business Bank Ltd.', 'site': 'http://www.tbb.ee/index_rus.html', 'country': 'Эстония',
     'ignore': False, 'address': 'г. Tallinn, Эстония', 'phoneNumber': '+372 6688 000'},
    {'name': 'Swedbank', 'site': 'https://www.swedbank.ee/private/home/more/pricesrates/rates?language=RUS',
     'country': 'Эстония', 'ignore': False, 'address': 'Таллинн, Эстония ', 'phoneNumber': '6310 310'},
    {'name': 'AB Sb Bank', 'site': 'https://www.sb.lt/ru/populiariausias-turinys-apie/valiutu-kursai-2-1-1/',
     'country': 'Литва', 'ignore': False, 'address': 'г. Шяуляй, Литва', 'phoneNumber': '+370 37 301 337'},
    {'name': 'AB SEB bankas', 'site': 'https://e.seb.lt/mainib/web.p?act=currencyrates&lang=ENG', 'country': 'Литва',
     'ignore': False, 'address': 'г. Паневежис, Литва', 'phoneNumber': '(+370 5) 268 2800'},
    {'name': 'Banca Transilvania SA', 'site': 'https://www.bancatransilvania.ro/curs-valutar-spot/',
     'country': 'Румыния', 'ignore': False, 'address': 'г. Клуж-Напока, Румыния', 'phoneNumber': '0264 308028  *8028'},
    {'name': 'ING Bank', 'site': 'https://www.ing.ro/ing-in-romania/informatii-utile/curs-valutar',
     'country': 'Румыния', 'ignore': False, 'address': 'г. Клуж-Напока, Румыния',
     'phoneNumber': '031 406 2464; 021 403 83 04; +40 21 222 16 00 '},
    {'name': 'Direktna banka', 'site': 'https://www.direktnabanka.rs/kursna-lista/', 'country': 'Сербия',
     'ignore': False, 'address': 'г. Београд, Сербия', 'phoneNumber': '+381 11 3208849'},
    {'name': 'Eurobank', 'site': 'https://www.eurobank.rs/home.1139.html', 'country': 'Сербия', 'ignore': False,
     'address': 'г. Апатин, Сербия', 'phoneNumber': '0800 1111 44; +381 11 2023 353'},
    {'name': 'NLB Banka', 'site': 'https://www.nlb.rs/strana/16591/kursne-liste', 'country': 'Сербия', 'ignore': False,
     'address': 'г. Београд, Сербия', 'phoneNumber': '011 7 15 15 22'},
    {'name': 'Raiffeisen banka', 'site': 'https://www.raiffeisenbank.rs/home.1400.html', 'country': 'Сербия',
     'ignore': False, 'address': 'г. Aranđelovac, Сербия', 'phoneNumber': '011/3202-100'},
    {'name': 'Sberbank', 'site': 'https://www.sberbank.rs/stanovnistvo', 'country': 'Сербия', 'ignore': False,
     'address': 'г. Београд, Сербия', 'phoneNumber': '0700 700 800'},
    {'name': 'Telenor Banka', 'site': 'http://www.telenorbanka.rs/en/consumer/', 'country': 'Сербия', 'ignore': False,
     'address': 'г. Београд, Сербия', 'phoneNumber': '063/9005'},
    {'name': 'VTB Banka AD', 'site': 'http://vtbbanka.rs/', 'country': 'Сербия', 'ignore': False,
     'address': 'г. Београд, Сербия', 'phoneNumber': '+381 11 395 2265'},
    {'name': 'Sberbank banka d.d.', 'site': 'https://www.sberbank.si/pripomocki/menjalnica?cust=2',
     'country': 'Словения', 'ignore': False, 'address': 'г. Pavšičeva, Словения',
     'phoneNumber': '+386 1 569 22 59, +386 5 666 12 56'},
    {'name': 'SKB banka d.d.', 'site': 'http://www.skb.si/en/exchange-rates/exchange-rates-for-individuals',
     'country': 'Словения', 'ignore': False, 'address': 'г. Ljubljana, Словения',
     'phoneNumber': '+386 (0)1 471 55 55; +386 (07) 305 27 85'},
    {'name': 'Bank of Ayudhya', 'site': 'https://www.krungsri.com/bank/en/Other/ExchangeRate/Todayrates.html',
     'country': 'Тайланд', 'ignore': False, 'address': 'г. Chang Wat Nonthaburi, Таиланд',
     'phoneNumber': '+66 2 423 3645'},
    {'name': 'Siam Commercial Bank', 'site': 'http://www.scb.co.th/scb_api/history_exchange.jsp', 'country': 'Тайланд',
     'ignore': False, 'address': 'г. Krung Thep Maha Nakhon, Таиланд', 'phoneNumber': '+66 2 248 1526'},
    {'name': 'China Everbright Bank', 'site': 'http://www.cebbank.com/eportal/ui?pageId=477263', 'country': 'Китай',
     'ignore': False, 'address': 'г. Пекин, Китай', 'phoneNumber': '010-56678827'},
    {'name': 'AS "Regional Investciju Banka"',
     'site': 'http://www.ribbank.com/ru/informacija/kursi_valjut/beznalichnie_dlja_rascheta', 'country': 'Латвия',
     'ignore': False, 'address': 'г. Рига, Латвия', 'phoneNumber': '+996 (312)  33 88 00 '},
    {'name': 'AS "Rigensis Bank"', 'site': 'http://www.rigensisbank.com/ru/valutas_kursi.html', 'country': 'Латвия',
     'ignore': False, 'address': 'г. Рига, Латвия', 'phoneNumber': '(+371) 67 55 55 51; 66 11 88 00'},
    {'name': 'АО "LPB Bank"', 'site': 'http://www.lpb.lv/ru/kursi-valut/', 'country': 'Латвия', 'ignore': False,
     'address': 'г. Рига, Латвия', 'phoneNumber': '(+371) 6 777 2 999'},
    {'name': 'AO "ЮниКредит Банк"', 'site': 'https://www.unicreditbank.ru/post.ucr.getRates.html', 'country': 'Россия',
     'ignore': False, 'address': 'г. Москва, Россия', 'phoneNumber': '+7 495 721-91-00'},
    {'name': 'CSOB', 'site': 'https://www.csob.cz/portal/lide/produkty/kurzovni-listky/kurzovni-listek',
     'country': 'Чехия', 'ignore': False, 'address': 'Чехия, Прага', 'phoneNumber': '+420 495 800 111'},
    {'name': 'Bank of Ireland',
     'site': 'https://personalbanking.bankofireland.com/bank/international-payments/daily-foreign-exchange-rates/',
     'country': 'Ирландия', 'ignore': False, 'address': 'Ирландия, Лимерик', 'phoneNumber': '+ 353 1 661 5933'},
    {'name': 'Cyprus Cooperative Bank', 'site': 'http://www.ccb.coop.com.cy/en/tools/currency/', 'country': 'Кипр',
     'ignore': False, 'address': 'Кипр, Никосия', 'phoneNumber': '+357 22743000'},
    {'name': 'BPI', 'site': 'https://www.bpiexpressonline.com/p/1/872/forex-rates', 'country': 'Филипины',
     'ignore': False, 'address': 'Филипины, Макати', 'phoneNumber': '+357 22743000'},
    {'name': 'BGZ BNP PARIBAS', 'site': 'https://www.bgzbnpparibas.pl/kursy-walut', 'country': 'Польша',
     'ignore': False, 'address': 'Польша, Варшава', 'phoneNumber': '+48 22 134 00 00'},
    {'name': 'Credir Agricole', 'site': 'https://www.credit-agricole.pl/klienci-indywidualni/kursy-walut',
     'country': 'Польша', 'ignore': False, 'address': 'Польша, Варшава', 'phoneNumber': '19019'},
    {'name': 'VUB BANKA', 'site': 'https://www.vub.sk/ludia/pre-kazdy-den/kurzovy-listok/', 'country': 'Словакия',
     'ignore': False, 'address': 'Словакия, Братислава', 'phoneNumber': '+421 2 4855 59 70 '},
    {'name': 'ЗАО «Агропромбанк»', 'site': 'https://www.agroprombank.com/info/rates.html', 'country': 'ПМР',
     'ignore': False, 'address': 'Приднестровье, г.Тирасполь', 'phoneNumber': '(533) 7-99-20'},
    {'name': 'ОАО «Эксимбанк»', 'site': 'http://bankexim.com/', 'country': 'ПМР', 'ignore': False,
     'address': 'Приднестровье, г.Тирасполь', 'phoneNumber': '0-8000-8000'},
    {'name': 'ЗАО "Приднестровский Сбербанк"', 'site': 'https://www.prisbank.com/', 'country': 'ПМР', 'ignore': False,
     'address': 'Приднестровье, г.Тирасполь', 'phoneNumber': '1611'},
    {'name': 'RCB', 'site': 'http://www.rcbcy.com/en/about-rcb/exchange-rates/', 'country': 'Кипр', 'ignore': False,
     'address': 'Кипр, г. Никосия', 'phoneNumber': '+357 25 355 722,  8 800 100 7722'},
    {'name': 'АК «Народный банк»', 'site': 'https://xb.uz/ru/interactive/rates', 'country': 'Узбекистан', 'ignore': False,
     'address': 'г. Ташкент, Узбекистан', 'phoneNumber': '+998 (71) 200-00-55'},
    {'name': 'ООО «Экспобанк»', 'site': 'https://expobank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 (495) 213 19 91'},
    {'name': 'ПАО Банк «АЛЕКСАНДРОВСКИЙ»', 'site': 'https://alexbank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Санкт-Петербург, Россия', 'phoneNumber': '8 800 222 87 07'},
    {'name': 'ООО "Кубань Кредит"', 'site': 'https://www.kubankredit.ru/person/vlozhit_i_zarabotat/kusy-valyut-i-metalov/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Краснодар, Россия', 'phoneNumber': '8 800 555 25 18, +7 861 2 777 888'},
    {'name': 'АО "Банк Уссури"', 'site': 'https://www.ussurybank.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Хабаровск, Россия', 'phoneNumber': '+7 (4212) 450-700'},
    {'name': 'ПАО «АК БАРС» БАНК', 'site': 'https://www.akbars.ru/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7-843-2-303-303'},
    {'name': 'ПАО "Банк ВТБ"', 'site': 'https://www.bm.ru/ru/iframe/kursy_valut/', 'country': 'Россия', 'ignore': False,
     'address': 'г. Москва, Россия', 'phoneNumber': '+7 800 200-23-26'},
    {'name': 'Tirana bank', 'site': 'http://www.tiranabank.al/english/d/79/80/136/exchange-rates/', 'country': 'Албания', 'ignore': False,
     'address': 'г. Тирана, Албания', 'phoneNumber': '+355 4 2281771'},
]

# text = '12312431 или (123)123-124321'
# pat = '(?:\d\s*)+'
# reg = re.compile(pat)
# print(reg.findall(text.replace('(', '').replace(')', '').replace('-', '').replace(' ', '')))
